<a href="https://colab.research.google.com/github/bbash/Data-Science-Assigment/blob/main/week__2_100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [239]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [240]:
print(np.__version__)
np.show_config()

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [241]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [242]:
item = np.zeros((10,10))
print("%d bytes" % (item.size * item.itemsize))

800 bytes


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [243]:
item = np.zeros(10)
item[4] = 1
print(item)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [244]:
item = np.arange(10,50)
print(item)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [245]:
item = item[::-1]
print(item)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [246]:
item = np.arange(9).reshape(3, 3)
print(item)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [247]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [248]:
identi = np.eye(3)
print(identi)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [249]:
item = np.random.random((3,3,3))
print(item)

[[[0.76891095 0.72912517 0.76794706]
  [0.20238095 0.19844386 0.92631472]
  [0.30574422 0.02279532 0.675877  ]]

 [[0.22422012 0.3010082  0.6664363 ]
  [0.31641361 0.2721113  0.12676615]
  [0.64973461 0.52591961 0.26267901]]

 [[0.76740699 0.18459887 0.84524069]
  [0.59786612 0.77369511 0.5322142 ]
  [0.04387722 0.35280478 0.751952  ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [250]:
item = np.random.random((10,10))
print(f'The max is {item.max():.4f}')
print(f'The min is {item.min():.4f}')


The max is 0.9986
The min is 0.0097


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [251]:
item = np.random.random(30).mean()
print(item)

0.466549807208427


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [252]:
item = np.ones((10,10))
item[1:-1,1:-1] = 0
item

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [253]:
item = np.ones((5,5))

# Using indexing
item[:, [0, -1]] = 0
item[[0, -1], :] = 0
print(item)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [254]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [255]:
item = np.diag(1+np.arange(4),k=-1)
item

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [256]:
shape = (6, 7, 8)
print(np.unravel_index(99, shape))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [257]:
# Define a single tile of the checkerboard
tile = np.array([[0, 1], [1, 0]])

# Use tile function to create the checkerboard matrix
checkerboard = np.tile(tile, (4, 4))

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [258]:
matrix = np.random.random((5,5))
normalized_matrix = matrix / np.max(np.abs(matrix))
normalized_matrix

array([[0.70289377, 0.54504641, 0.51034128, 0.76945289, 1.        ],
       [0.32474973, 0.64474254, 0.14250395, 0.46327824, 0.61216015],
       [0.85530449, 0.08967405, 0.92985388, 0.37644125, 0.7853963 ],
       [0.26925795, 0.82621094, 0.87753389, 0.73954225, 0.21603463],
       [0.9083613 , 0.36416762, 0.72022882, 0.30005206, 0.36459115]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [259]:
# Define custom dtype for RGBA color
color_dtype = np.dtype([('R', np.uint8),   # Red channel
                        ('G', np.uint8),   # Green channel
                        ('B', np.uint8),   # Blue channel
                        ('A', np.uint8)])  # Alpha channel

# Example usage:
color = np.array((255, 0, 0, 255), dtype=color_dtype)  # Red color with full opacity
print(color)

(255, 0, 0, 255)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [260]:
matrix1 = np.random.random((5, 3))

# Create a 3x2 matrix
matrix2 = np.random.random((3, 2))

# Perform matrix multiplication
result = matrix1 @ matrix2

# Alternatively, you can use np.dot(matrix1, matrix2)
# result = np.dot(matrix1, matrix2)

print(result)

[[1.74868951 1.9501608 ]
 [0.33693111 0.36156627]
 [0.38171635 0.45889411]
 [0.83257876 1.00993793]
 [1.46315041 1.79429945]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [261]:
arr = np.array([1, 4, 6, 9, 3, 7, 2, 5, 8])

arr[(arr > 3) & (arr < 8)] *= -1

print(arr)

[ 1 -4 -6  9  3 -7  2 -5  8]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [262]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [263]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆)

In [264]:
float_array = np.array([-3.5, -2.7, -1.2, 0.0, 1.2, 2.7, 3.5])

rounded_array = np.where(float_array >= 0, np.ceil(float_array), np.floor(float_array))

print(rounded_array)

[-4. -3. -2.  0.  2.  3.  4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [265]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

common_values = np.intersect1d(array1, array2)

print(common_values)

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [266]:
# Ignore all NumPy warnings
np.seterr(all='ignore')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [267]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [268]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [269]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [270]:
A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6])

np.add(A, B, out=A)
np.divide(-A, 2, out=A, casting='unsafe')  # Specify casting='unsafe' to allow conversion of float to int
np.multiply(A, B, out=A)

print(A)

[-10.  -17.5 -27. ]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [271]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[0. 0. 3. 4. 3. 3. 0. 1. 2. 2.]
[0. 0. 3. 4. 3. 3. 0. 1. 2. 2.]
[0. 0. 3. 4. 3. 3. 0. 1. 2. 2.]
[0 0 3 4 3 3 0 1 2 2]
[0. 0. 3. 4. 3. 3. 0. 1. 2. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [272]:
matrix = np.zeros((5, 5))
matrix += np.arange(5)

print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [273]:

def integer_generator():
    for i in range(10):
        yield i

array = np.fromiter(integer_generator(), dtype=int)

print(array)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [274]:

vector = np.linspace(0, 1, 12)[1:-1]

print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [275]:
vector = np.random.rand(10)
vector.sort()

print(vector)

[0.05042996 0.17851869 0.24263557 0.41874739 0.47718069 0.48312314
 0.57203355 0.64528443 0.70924476 0.8228487 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [276]:
array = np.array([1, 2, 3, 4, 5])

sum_array = np.add.reduce(array)

print(sum_array)

15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [277]:

# Generate random arrays A and B
A = np.random.rand(5)
B = np.random.rand(5)

# Check if arrays A and B are equal
are_equal = np.array_equal(A, B)

print(are_equal)

False


### 43. Make an array immutable (read-only)

In [278]:
arr = np.array([1, 2, 3, 4, 5])

# Make the array immutable
arr.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [279]:
cartesian_coords = np.random.rand(10, 2)

# Convert Cartesian coordinates to polar coordinates
x, y = cartesian_coords[:, 0], cartesian_coords[:, 1]
rho = np.hypot(x, y)
theta = np.arctan2(y, x)

polar_coords = np.column_stack((rho, theta))

print(polar_coords)

[[0.64968581 0.39256549]
 [0.47157165 1.27233014]
 [0.41320678 1.26143291]
 [0.61952644 0.08204686]
 [0.38260697 0.99315201]
 [0.8786584  1.40745167]
 [0.99980334 0.78570558]
 [0.93807588 0.86354071]
 [0.35314797 0.93172479]
 [1.0093549  0.79671372]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [280]:
vector = np.random.rand(10)

# Find the index of the maximum value
max_index = np.argmax(vector)

# Replace the maximum value by 0
vector[max_index] = 0

print(vector)

[0.79357057 0.45957926 0.31396945 0.72158488 0.4079229  0.
 0.1437091  0.71724699 0.26834089 0.79658097]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [281]:
dtype = [('x', float), ('y', float)]

# Generate x and y coordinates covering [0,1]x[0,1]
x = np.linspace(0, 1, 10)
y = np.linspace(0, 1, 10)

# Create the structured array
structured_array = np.zeros((10, 10), dtype=dtype)
structured_array['x'], structured_array['y'] = np.meshgrid(x, y)

print(structured_array)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [282]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Construct the Cauchy matrix C
C = 1 / (X[:, np.newaxis] - Y)

print(C)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 49. How to print all the values of an array? (★★☆)

In [283]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Print all values of the array
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [284]:
vector = np.array([1, 3, 5, 7, 9])

# Given scalar
scalar = 4

# Find index of closest value
closest_index = np.abs(vector - scalar).argmin()

# Closest value
closest_value = vector[closest_index]

print(closest_value)

3


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [285]:
dtype = [('position', [('x', float), ('y', float)]),
         ('color', [('r', int), ('g', int), ('b', int)])]

# Create a structured array
structured_array = np.zeros(1, dtype=dtype)

# Set values for position and color
structured_array['position']['x'] = 10.0
structured_array['position']['y'] = 20.0
structured_array['color']['r'] = 255
structured_array['color']['g'] = 128
structured_array['color']['b'] = 0

print(structured_array)

[((10., 20.), (255, 128, 0))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [286]:
from scipy.spatial.distance import cdist

# Generate random vector of shape (100, 2) representing coordinates
coordinates = np.random.rand(100, 2)

# Compute point-by-point distances
distances = cdist(coordinates, coordinates)

print(distances)

[[0.         0.13252658 0.36776415 ... 0.09436096 0.12033351 0.72420503]
 [0.13252658 0.         0.25971153 ... 0.0548464  0.17398732 0.68042032]
 [0.36776415 0.25971153 0.         ... 0.2748204  0.32056008 0.48294723]
 ...
 [0.09436096 0.0548464  0.2748204  ... 0.         0.11974534 0.66135638]
 [0.12033351 0.17398732 0.32056008 ... 0.11974534 0.         0.61350598]
 [0.72420503 0.68042032 0.48294723 ... 0.66135638 0.61350598 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [287]:
float_array = np.array([1.5, 2.5, 3.5], dtype=np.float32)

# Convert the float array to an integer (32 bits) array in place
float_array.view(dtype=np.int32)

print(float_array)

[1.5 2.5 3.5]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [288]:
#with open('filename.txt', 'r') as file:
    # Read the entire contents of the file
 #   contents = file.read()

# Print the contents of the file
#print(contents)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [289]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Enumerate over the array
for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [290]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [291]:
# Size of the 2D array
rows, cols = 5, 5

# Number of elements to randomly place
p = 5

# Create a 2D array filled with zeros
arr = np.zeros((rows, cols), dtype=int)

# Generate random indices
indices = np.random.choice(rows * cols, p, replace=False)

# Place random elements at the chosen indices
arr.flat[indices] = 1

print(arr)

[[0 0 1 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [292]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)
Y

array([[ 0.13780757,  0.14109777, -0.15204898,  0.195359  , -0.37609557,
         0.29963727,  0.09511588,  0.20568163, -0.19505815, -0.35149642],
       [-0.14602815, -0.43350261,  0.13672532, -0.03996562,  0.05431944,
        -0.40450542,  0.19053078,  0.2854897 ,  0.38557694, -0.02864038],
       [ 0.0400008 ,  0.16948145,  0.16349122,  0.41926865, -0.25895898,
         0.10368083, -0.34344872, -0.20060414,  0.32866609, -0.4215772 ],
       [-0.00377965, -0.28606444,  0.38133812, -0.51084518,  0.11155401,
         0.34122284,  0.27017013, -0.29114484, -0.32455409,  0.31210309],
       [-0.02586304, -0.21162337,  0.35752495, -0.15208277, -0.28656574,
         0.59857535, -0.35922009,  0.28075314, -0.03242794, -0.16907048]])

#### 59. How to sort an array by the nth column? (★★☆)

In [293]:
# Create an example array
arr = np.array([[1, 4, 3],
                [2, 3, 1],
                [3, 2, 2]])

# Define the column index to sort by (0-based indexing)
n = 1

# Get the indices that would sort the array by the nth column
indices = np.argsort(arr[:, n])

# Rearrange the rows of the array based on the sorted indices
sorted_arr = arr[indices]

print(sorted_arr)

[[3 2 2]
 [2 3 1]
 [1 4 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [294]:
# Create an example 2D array
arr = np.array([[1, 0, 3],
                [0, 0, 0],
                [0, 0, 0]])

# Check if any column contains all zeros
null_columns = np.all(arr == 0, axis=0)

print(null_columns)

[False  True False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [295]:
# Example array
arr = np.array([1, 3, 5, 7, 9])

# Given value
value = 6

# Find index of nearest value
nearest_index = np.abs(arr - value).argmin()

# Nearest value
nearest_value = arr[nearest_index]

print(nearest_value)

5


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [296]:
# Define the arrays
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5], [6]])

# Initialize the sum
total_sum = 0

# Iterate over the elements of both arrays and compute the sum
for a, b in zip(array1.flat, array2.flat):
    total_sum += a + b

print(total_sum)

21


#### 63. Create an array class that has a name attribute (★★☆)

In [297]:
class NamedArray:
    def __init__(self, name, data):
        self.name = name
        self.data = np.array(data)

# Example usage:
my_array = NamedArray("example", [[1, 2, 3], [4, 5, 6]])
print("Name:", my_array.name)
print("Data:", my_array.data)

Name: example
Data: [[1 2 3]
 [4 5 6]]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [298]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 4. 2. 2. 3. 3. 3. 3. 4. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [299]:
X = np.array([1, 2, 3, 4, 5])

# Example index list I
I = np.array([1, 3, 2, 1, 0])

# Example array F
F = np.zeros(4)

# Accumulate elements of X into F based on the index list I
np.add.at(F, I, X)

print(F)

[5. 5. 3. 2.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [300]:
# Example image with shape (w, h, 3)
image = np.random.randint(0, 256, size=(10, 10, 3), dtype=np.uint8)

# Flatten the image along the color channels
flattened_image = image.reshape(-1, 3)

# Compute the number of unique colors
num_unique_colors = len(np.unique(flattened_image, axis=0))

print(num_unique_colors)

100


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [301]:
# Create a four-dimensional array (example)
array = np.random.randint(0, 10, size=(2, 3, 4, 5))

# Get the sum over the last two axes
sum_last_two_axes = np.sum(array, axis=(-1, -2))

print(sum_last_two_axes)

[[ 80  70 100]
 [ 72  82  88]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [302]:
D = np.array([1, 2, 3, 4, 5])

# Example vector S describing subset indices
S = np.array([0, 1, 0, 1, 1])

# Get the unique subset indices
subset_indices = np.unique(S)

# Compute the means of subsets of D
subset_means = [np.mean(D[S == i]) for i in subset_indices]

print(subset_means)

[2.0, 3.6666666666666665]


#### 69. How to get the diagonal of a dot product? (★★★)

In [303]:
# Create two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Compute the dot product
dot_product = np.dot(A, B)

# Get the diagonal of the dot product
diagonal = np.diagonal(dot_product)

print(diagonal)

[19 50]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [304]:
# Create an array of dimension (5, 5, 3)
array_3d = np.random.randint(0, 10, size=(5, 5, 3))

# Create an array with dimensions (5, 5)
array_2d = np.random.randint(0, 10, size=(5, 5))

# Multiply the 3D array by the 2D array
result = array_3d * array_2d[:, :, np.newaxis]

print(result)

[[[45  5 20]
  [35 28 63]
  [24 36 42]
  [12 18 42]
  [35 63 42]]

 [[ 9 18  6]
  [16  6  4]
  [ 5  0  5]
  [32 28 12]
  [56 21 14]]

 [[ 0  6 21]
  [56 21 63]
  [24 12 12]
  [ 0  0  0]
  [ 8  5  3]]

 [[27 63 72]
  [12  9 18]
  [40 30 40]
  [27  0  3]
  [ 8 16  0]]

 [[12 14  0]
  [21 12  3]
  [ 0 24  6]
  [36 30 48]
  [27 81 81]]]


#### 72. How to swap two rows of an array? (★★★)

In [305]:
# Create an example array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Swap rows 0 and 1
arr[0], arr[1] = arr[1], arr[0]

print(arr)

[[4 5 6]
 [4 5 6]
 [7 8 9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [306]:
# Example set of 10 triplets describing triangles (shared vertices)
triplets = [
    ((0, 0), (1, 1), (2, 2)),
    ((1, 1), (2, 2), (3, 3)),
    ((2, 2), (3, 3), (4, 4)),
    ((3, 3), (4, 4), (5, 5)),
    ((4, 4), (5, 5), (6, 6)),
    ((5, 5), (6, 6), (7, 7)),
    ((6, 6), (7, 7), (8, 8)),
    ((7, 7), (8, 8), (9, 9)),
    ((8, 8), (9, 9), (0, 0)),
    ((9, 9), (0, 0), (1, 1))
]

# Create a set to store unique line segments
unique_segments = set()

# Iterate over each triplet and extract line segments
for triplet in triplets:
    # Extract line segments from the triplet
    segments = [(triplet[i], triplet[i + 1]) for i in range(len(triplet) - 1)]
    segments.append((triplet[-1], triplet[0]))  # Close the loop

    # Add line segments to the set of unique line segments
    unique_segments.update(segments)

print(unique_segments)

{((4, 4), (5, 5)), ((9, 9), (7, 7)), ((7, 7), (5, 5)), ((3, 3), (4, 4)), ((8, 8), (9, 9)), ((1, 1), (9, 9)), ((1, 1), (2, 2)), ((5, 5), (6, 6)), ((3, 3), (1, 1)), ((4, 4), (2, 2)), ((0, 0), (1, 1)), ((8, 8), (6, 6)), ((2, 2), (3, 3)), ((6, 6), (7, 7)), ((9, 9), (0, 0)), ((0, 0), (8, 8)), ((7, 7), (8, 8)), ((2, 2), (0, 0)), ((6, 6), (4, 4)), ((5, 5), (3, 3))}


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [307]:
# Example sorted array C (bincount)
C = np.array([0, 1, 2, 3, 4, 5])

# Compute the range of values based on the length of C
max_value = len(C) - 1

# Create the array A
A = np.repeat(np.arange(max_value + 1), C)

print(A)

[1 2 2 3 3 3 4 4 4 4 5 5 5 5 5]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [308]:
def sliding_window_average(arr, window_size):
    # Define the kernel for computing the sliding window average
    kernel = np.ones(window_size) / window_size

    # Use np.convolve to compute the sliding window average
    averages = np.convolve(arr, kernel, mode='valid')

    return averages

# Example array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Sliding window size
window_size = 3

# Compute sliding window averages
averages = sliding_window_average(arr, window_size)

print(averages)

[2. 3. 4. 5. 6. 7. 8. 9.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [309]:
# Example one-dimensional array Z
Z = np.array([1, 2, 3, 4, 5, 6])

# Build the two-dimensional array
n = 3  # Number of elements per row
rows = len(Z) - n + 1  # Number of rows
result = np.vstack([Z[i:i+n] for i in range(rows)])

print(result)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [310]:
# Example boolean variable
boolean_var = True


print(not boolean_var)  # False

False


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [311]:
# Example sets of points P0 and P1 describing lines
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [2, 1], [3, 2]])

# Example point p
p = np.array([1, 0])

# Compute distance from p to each line
distances = [np.linalg.norm(np.cross(p - p0, p1 - p0)) / np.linalg.norm(p1 - p0) for p0, p1 in zip(P0, P1)]

print(distances)

[0.0, 1.0, 2.0]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [312]:
# Example sets of points P0 and P1 describing lines
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [2, 1], [3, 2]])

# Example set of points P
P = np.array([[1, 1], [2, 2], [3, 3]])

# Compute distance from each point in P to each line
distances = [[np.linalg.norm(np.cross(P[j] - P0[i], P1[i] - P0[i])) / np.linalg.norm(P1[i] - P0[i]) for i in range(len(P0))] for j in range(len(P))]

print(distances)

[[1.0, 0.0, 1.0], [2.0, 1.0, 0.0], [3.0, 2.0, 1.0]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [313]:
def extract_subpart(arr, shape, center, fill_value=0):
    pad_width = [(max(0, center[i] - shape[i] // 2), max(0, (shape[i] + 1) // 2 - (arr.shape[i] - center[i]))) for i in range(arr.ndim)]
    return np.pad(arr, pad_width, mode='constant', constant_values=fill_value)[tuple(slice(max(0, center[i] - shape[i] // 2), min(arr.shape[i], center[i] + (shape[i] + 1) // 2)) for i in range(arr.ndim))]

# Example usage:
arr = np.arange(25).reshape(5, 5)
subpart = extract_subpart(arr, (3, 3), (2, 2))
print(subpart)

[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [314]:
# Original array Z
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# Generate array R
R = [Z[i:i+4] for i in range(len(Z) - 3)]

print(R)

[array([1, 2, 3, 4]), array([2, 3, 4, 5]), array([3, 4, 5, 6]), array([4, 5, 6, 7]), array([5, 6, 7, 8]), array([6, 7, 8, 9]), array([ 7,  8,  9, 10]), array([ 8,  9, 10, 11]), array([ 9, 10, 11, 12]), array([10, 11, 12, 13]), array([11, 12, 13, 14])]


#### 82. Compute a matrix rank (★★★)

In [315]:
# Example matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print("Rank of the matrix:", rank)

Rank of the matrix: 2


#### 83. How to find the most frequent value in an array?

In [316]:
# Example array
arr = np.array([1, 2, 3, 4, 1, 2, 2, 3, 2, 2, 2])

# Find the most frequent value
most_frequent_value = np.argmax(np.bincount(arr))

print("Most frequent value:", most_frequent_value)

Most frequent value: 2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [317]:
# Generate a random 10x10 matrix
matrix = np.random.randint(0, 100, size=(10, 10))

# Extract all contiguous 3x3 blocks
blocks = [matrix[i:i+3, j:j+3] for i in range(8) for j in range(8)]

# Print the extracted blocks
for block in blocks:
    print(block)
    print()

[[98 21 98]
 [46 14 90]
 [35  6 72]]

[[21 98 41]
 [14 90 82]
 [ 6 72 38]]

[[98 41 18]
 [90 82 17]
 [72 38 36]]

[[41 18  1]
 [82 17 64]
 [38 36 35]]

[[18  1 62]
 [17 64 36]
 [36 35 77]]

[[ 1 62 16]
 [64 36 57]
 [35 77 25]]

[[62 16 90]
 [36 57 35]
 [77 25 55]]

[[16 90 90]
 [57 35 54]
 [25 55 73]]

[[46 14 90]
 [35  6 72]
 [40 29 79]]

[[14 90 82]
 [ 6 72 38]
 [29 79 32]]

[[90 82 17]
 [72 38 36]
 [79 32 49]]

[[82 17 64]
 [38 36 35]
 [32 49 68]]

[[17 64 36]
 [36 35 77]
 [49 68 29]]

[[64 36 57]
 [35 77 25]
 [68 29 50]]

[[36 57 35]
 [77 25 55]
 [29 50 30]]

[[57 35 54]
 [25 55 73]
 [50 30  2]]

[[35  6 72]
 [40 29 79]
 [42 88 98]]

[[ 6 72 38]
 [29 79 32]
 [88 98 93]]

[[72 38 36]
 [79 32 49]
 [98 93 62]]

[[38 36 35]
 [32 49 68]
 [93 62 82]]

[[36 35 77]
 [49 68 29]
 [62 82  8]]

[[35 77 25]
 [68 29 50]
 [82  8 69]]

[[77 25 55]
 [29 50 30]
 [ 8 69 25]]

[[25 55 73]
 [50 30  2]
 [69 25 38]]

[[40 29 79]
 [42 88 98]
 [29 66 91]]

[[29 79 32]
 [88 98 93]
 [66 91 45]]

[[79 32 49]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [318]:
# Example 16x16 array
array = np.random.randint(0, 10, size=(16, 16))

# Define block size
block_size = 4

# Compute block sum
block_sum = np.zeros((16 // block_size, 16 // block_size), dtype=array.dtype)
for i in range(0, 16, block_size):
    for j in range(0, 16, block_size):
        block_sum[i // block_size, j // block_size] = np.sum(array[i:i+block_size, j:j+block_size])

print(block_sum)

[[47 78 68 63]
 [62 91 75 78]
 [56 85 69 75]
 [74 62 97 71]]


#### 89. How to get the n largest values of an array (★★★)

In [319]:
# Example array
arr = np.array([1, 5, 2, 7, 3, 9, 4, 6, 8])

# Number of largest values to retrieve
n_largest = 3

# Get the indices of the n largest values
indices = np.argsort(arr)[-n_largest:]

# Get the n largest values
largest_values = arr[indices]

print("Indices of the n largest values:", indices)
print("The n largest values:", largest_values)

Indices of the n largest values: [3 8 5]
The n largest values: [7 8 9]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [320]:
import itertools

# Example vectors
vectors = [[1, 2], [3, 4], [5, 6]]

# Build the Cartesian product
cartesian_product = list(itertools.product(*vectors))

print(cartesian_product)

[(1, 3, 5), (1, 3, 6), (1, 4, 5), (1, 4, 6), (2, 3, 5), (2, 3, 6), (2, 4, 5), (2, 4, 6)]


#### 91. How to create a record array from a regular array? (★★★)

In [321]:
# Example vectors
vectors = [[1, 2], [3, 4], [5, 6]]

# Build the Cartesian product
cartesian_product = list(itertools.product(*vectors))

print(cartesian_product)

[(1, 3, 5), (1, 3, 6), (1, 4, 5), (1, 4, 6), (2, 3, 5), (2, 3, 6), (2, 4, 5), (2, 4, 6)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [322]:
# Method 1: Using np.power()
Z_cubed_method1 = np.power(Z, 3)

In [323]:
# Method 2: Using the exponentiation operator **
Z_cubed_method2 = Z ** 3

In [324]:
# Method 3: Using element-wise multiplication
Z_cubed_method3 = Z * Z * Z

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [325]:
import numpy as np

# Example 10x3 matrix
matrix = np.random.randint(0, 3, size=(10, 3))

# Extract rows with unequal values
unequal_rows = matrix[np.any(matrix != matrix[:, 0][:, None], axis=1)]

print(unequal_rows)

[[2 0 1]
 [2 1 1]
 [1 2 0]
 [2 0 2]
 [2 1 2]
 [1 2 2]
 [0 1 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [326]:
# Example two-dimensional array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [1, 2, 3],
                  [7, 8, 9],
                  [4, 5, 6]])

# Extract unique rows
unique_rows = np.unique(array, axis=0)

print(unique_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [327]:
def equidistant_samples(X, Y, num_samples):
    # Calculate the cumulative distance along the path
    cumulative_distance = np.cumsum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2))
    cumulative_distance = np.insert(cumulative_distance, 0, 0)  # Insert 0 at the beginning

    # Interpolate the path
    t_interpolated = np.linspace(0, cumulative_distance[-1], num_samples)
    X_interpolated = np.interp(t_interpolated, cumulative_distance, X)
    Y_interpolated = np.interp(t_interpolated, cumulative_distance, Y)

    return X_interpolated, Y_interpolated

# Example path described by two vectors X and Y
X = np.array([0, 1, 3, 6, 10])
Y = np.array([0, 2, 5, 7, 8])

# Number of equidistant samples
num_samples = 20

# Sample the path using equidistant samples
X_samples, Y_samples = equidistant_samples(X, Y, num_samples)

print("Equidistant samples X:", X_samples)
print("Equidistant samples Y:", Y_samples)

Equidistant samples X: [ 0.          0.31941116  0.63882231  0.95823347  1.34437578  1.74055656
  2.13673734  2.53291812  2.9290989   3.48791953  4.0821907   4.67646187
  5.27073305  5.86500422  6.53549957  7.22839966  7.92129974  8.61419983
  9.30709991 10.        ]
Equidistant samples Y: [0.         0.63882231 1.27764463 1.91646694 2.51656367 3.11083484
 3.70510601 4.29937719 4.89364836 5.32527969 5.72146047 6.11764125
 6.51382203 6.91000281 7.13387489 7.30709991 7.48032494 7.65354996
 7.82677498 8.        ]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [328]:
def select_multinomial_draws(X, n):
    return X[(np.all(np.equal(np.mod(X, 1), 0), axis=1)) & (np.sum(X, axis=1) == n)]

# Example 2D array X
X = np.array([[1, 2, 3],
              [2, 3, 5],
              [1, 1.5, 2.5],
              [3, 4, 5]])

# Integer n
n = 6

# Select rows representing multinomial draws with n degrees
selected_rows = select_multinomial_draws(X, n)

print("Selected rows:")
print(selected_rows)

Selected rows:
[[1. 2. 3.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [329]:
def bootstrap_confidence_interval(X, num_samples=1000, alpha=0.05):
    # Resample with replacement and compute means
    means = np.random.choice(X, size=(num_samples, len(X)), replace=True).mean(axis=1)

    # Compute percentiles for confidence interval
    lower_bound, upper_bound = np.percentile(means, [100 * (alpha / 2), 100 * (1 - alpha / 2)])
    return lower_bound, upper_bound

# Example 1D array X
X = np.random.normal(loc=10, scale=2, size=100)

# Compute bootstrapped 95% confidence interval for the mean of X
lower_bound, upper_bound = bootstrap_confidence_interval(X)

print("95% confidence interval for the mean of X:", (lower_bound, upper_bound))

95% confidence interval for the mean of X: (9.677712816189157, 10.472011100597152)
